Using service loader mediator annotations (see #630).
jakartaee/mail-api pull request #632
Opened 2022-10-23 13:06 UTC by mnlipp

Shows the usage of the [service locator mediator](https://github.com/eclipse-ee4j/mail/issues/630) with annotations that generate the "Require-Capability" header in MANIFEST.MF. (Alternatively the Header can be specified directly in pom.xml.)

The Providers (in angus-mail) need a corresponding `@ServiceProvider` annotation such as:
```
@aQute.bnd.annotation.spi.ServiceProvider(value = StreamProvider.class)
public class MailStreamProvider implements StreamProvider {
```

(Sorry, can't provide a PR for that, maven compilation for angus-mail doesn't work.)

2022-10-25 07:00 UTC, jbescos commented
I wrote in the issue by mistake. Find the comment here:
https://github.com/jakartaee/mail-api/issues/630#issuecomment-1290056613

2022-10-25 07:12 UTC, mnlipp commented
> Ideally there should be a plugin to deal with the manifest. 

You don't need an extra plugin. You can simply add this information using the Felix maven bundle plugin which is already in pom.xml with instructions `<Provide-Capability>` and `<Require-Capability>` (that's doing it "manually", see https://github.com/jakartaee/mail-api/issues/630#issuecomment-1287852918). In general, the manual approach is considered a bit more difficult to maintain, but once it's there, it rarely changes (only if you add another loaded service).

If it helps, I can provide another PR with the pom.xml based solution.

2022-11-02 11:51 UTC, lukasj commented on api/src/main/java/jakarta/mail/Session.java
> +@aQute.bnd.annotation.spi.ServiceConsumer(value = Provider.class)
There is currently a restriction on using 3rd party libraries in the APIs and only (non Java SE/Jakarta EE packages can be used.

2022-11-02 11:52 UTC, lukasj requested changes
It is currently not allowed to depend on 3rd party libraries from APIs

2022-11-02 12:00 UTC, mnlipp commented
> It is currently not allowed to depend on 3rd party libraries from APIs

This is why this has actually been superseded by https://github.com/jakartaee/mail-api/pull/633.

2022-11-02 12:01 UTC, lukasj commented
so this should have been closed then

2022-11-02 12:01 UTC, closed without merging